### ISSUE TITLE
All namespaces not used in node type definitions missing from the export

### ISSUE THREAD

**Issue by stefanseifert** [Netcentric/aem-nodetypes#2]
filevault package validation outputs a warning like this
```
[WARNING] ValidationViolation: "jackrabbit-nodetypes: crx: is not a registered namespace prefix. Skip validation of nodes with that type/name", filePath=jcr_root\conf\filevaultsample\settings\wcm\policies\_rep_policy.xml, nodePath=/conf/filevaultsample/settings/wcm/policies/rep:policy/allow1, line=11, column=49
```

if the package contains an ACL definition with a rule like this:
```
    <allow1
        jcr:primaryType="rep:GrantACE"
        rep:principalName="content-authors"
        rep:privileges="{Name}[crx:replicate,jcr:read]"/>
```

the `crx` namespace is missing from the cnd files here.

a lot of other namespaces are missing as well (e.g. all those that are often used in DAM metadata like `Iptc4xmpCore`. by what process was the list of namespaces defined? manually or in some automatic process?

**Comment by kwin** [comment]
> by what process was the list of namespaces defined? manually or in some automatic process?

This is explained in https://github.com/Netcentric/aem-nodetypes/blob/a201c769454b3cd9ef6cf1f1193f2ab811899d43/src/main/resources/aem.cnd#L14

I don't know why the crx namespace is not contained in that dump. @stefanseifert Do you have any idea how to get the full dump?

**Comment by kwin** [comment]
I just checked http://localhost:4502/crx/explorer/nodetypes/list.jsp?view=cnf&selection= and also that does not have the crx namespace....

**Comment by stefanseifert** [comment]
it's there if you look at http://localhost:4502/crx/explorer/ui/namespace_editor.jsp?ck=1606407982435&Path=&Callback=reload

probably the export contains only namespaces defined by CND files, and not those that are added dynamically during the livetime of a repository? (iirc this happens e.g. when uploading assets, they may contain namespaces not known before)

**Comment by kwin** [comment]
The code behind  http://localhost:4502/crx/explorer/nodetypes/list.jsp?view=cnf&selection= looks like this

```
...
 if (req.getParameter("view", "").equalsIgnoreCase("cnf")) {
        response.setContentType("text/plain; charset=utf-8");
        CompactNodeTypeDefWriter cnd = new CompactNodeTypeDefWriter((Writer)out, repSession, true);
        if (ntMgr == null) {
          NodeTypeIterator<NodeType> nodeTypeIterator = repSession.getWorkspace().getNodeTypeManager().getAllNodeTypes();
          while (nodeTypeIterator.hasNext()) {
            NodeType ntImpl = nodeTypeIterator.next();
            if (nodeTypeFilter == 1 && !ntImpl.isMixin())
              continue; 
            if (nodeTypeFilter == 2 && ntImpl.isMixin())
              continue; 
            cnd.write((NodeTypeDefinition)ntImpl);
          } 
        }
...
```

Probably one would need to call http://jackrabbit.apache.org/api/2.20/org/apache/jackrabbit/commons/cnd/CompactNodeTypeDefWriter.html#write-java.util.Collection-org.apache.jackrabbit.commons.cnd.CompactNodeTypeDefWriter.NamespaceMapping-java.io.Writer- instead internally. I will investigate, whether there is a servlet exposing that. Otherwise I fear I have to come up with my own implementation for doing a full export.

**Comment by stefanseifert** [comment]
namespaces defined in bundle headers like
```
Sling-Namespaces: wcmio=http://wcm.io/ns
```
are also not contained in the output of `exportnodetype.jsp`.

**Comment by kwin** [comment]
Are those used in nodetypes? 
I would rather assume that only namespaces used in nodetypes are exported, the others not. Compare with https://github.com/Netcentric/aem-nodetypes/issues/2#issuecomment-734402595

**Comment by stefanseifert** [comment]
no - but the namespace may by used by properties stored in content packages

**Comment by kwin** [comment]
Just to clarify: I do agree that this is a bug and we must export all namespaces, the only question is how to achieve this easily.

**Comment by kwin** [comment]
This version: 
[aem-2020.11.4506.20201112T235200Z.cnd.txt](https://github.com/Netcentric/aem-nodetypes/files/5604603/aem-2020.11.4506.20201112T235200Z.cnd.txt) has been created with a custom servlet now (I will push that later as well).
@stefanseifert WDYT?

**Comment by stefanseifert** [comment]
looks good!
it think this line should be omitted:
```
<''=''>
```

**Comment by kwin** [comment]
https://issues.apache.org/jira/browse/OAK-9289

**Comment by stefanseifert** [comment]
thanks!
maybe you should publish an updated version of the AEM 6.5 node type set as well with all namespaces?

**Comment by kwin** [comment]
@stefanseifert Would you be able to provide a PR for 6.5.7?

**Comment by stefanseifert** [comment]
done, created 2 PRs
