### ISSUE TITLE
Missing node type cfVariationNode regarding Content Fragments

### ISSUE THREAD

**Issue by AnselmHa** [Netcentric/aem-nodetypes#7]
<version>6.5.7.0</version>
[WARNING] ValidationViolation: "jackrabbit-nodetypes: {http://www.day.com/dam/1.0}cfVariationNode Skip validation of nodes with that type/name", filePath=jcr_root/content/dam/content-fragments/b2c/test-content/.../.content.xml, nodePath=/content/dam/content-fragments/b2c/test-content/.../jcr:content/data/master, line=25, column=66

This dam:cfVariationNode is automatically created when creating a Content Fragments.
<jcr:root xmlns:dam="http://www.day.com/dam/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
...
            <master
                    jcr:mixinTypes="[cq:Taggable,dam:cfVariationNode]"
                    jcr:primaryType="nt:unstructured"

Would it be possible to add that node type or is it an AEM lib missing that type?
        <aem.sdk.api>2022.10.9145.20221006T013555Z-220800</aem.sdk.api>

**Comment by kwin** [comment]
@AnselmHa This node type has been added recently. I just released a new version `2022.10.0` which should hit Maven Central soon.
